"""Init

Revision ID: 4bcffc2d8dc4
Revises: 
Create Date: 2024-11-11 15:16:16.923278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcffc2d8dc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links_table',
    sa.Column('link_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('subreddit', sa.String(), nullable=True),
    sa.Column('nsfw_flag', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_links_table_url'), 'links_table', ['url'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=True),
    sa.Column('links_requested', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('joined_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('files_table',
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_order', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links_table.link_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'file_id'),
    sa.UniqueConstraint('link_id', 'file_order', name='_link_id_file_order_uc')
    )
    op.create_index('ix_files_table_link_id', 'files_table', ['link_id'], unique=False)
    op.create_table('user_links',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links_table.link_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'link_id')
    )
    op.create_index(op.f('ix_user_links_link_id'), 'user_links', ['link_id'], unique=False)
    op.create_index('ix_user_links_user_id', 'user_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_links_user_id', table_name='user_links')
    op.drop_index(op.f('ix_user_links_link_id'), table_name='user_links')
    op.drop_table('user_links')
    op.drop_index('ix_files_table_link_id', table_name='files_table')
    op.drop_table('files_table')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_links_table_url'), table_name='links_table')
    op.drop_table('links_table')
    # ### end Alembic commands ###
